### ISSUE TITLE
Wiki-Review

### ISSUE THREAD

**Issue by PaulFrost** [TUBSAPISS2017/projektarbeit-beispiel#1]
Könnt ihr das Wiki durchlesen und mir euer Feedback geben?

**Comment by JustusDroege** [comment]
Es sollte seine Aufgabe erfüllen und den Teilnehmern eine gute Orientierung liefern. 
Hab 2 Schreibfehler korrigiert. Im Usecase fehlt noch ein "n" bei "Daten der verliehenen Kits".

**Comment by Marc-K** [comment]
Bin auch der Meinung, dass es so verständlich sein sollte. Als Git-Neuling werde ich die Schritte auf der Home-Seite demnächst durchgehen und dann Feedback geben.

**Comment by paulypeter** [comment]
Ich finde es so weit verständlich!
Vielleicht sollten die Bezeichnungen in den Use-Case-Diagrammen auf die in der Übung vorgestellten Begriffe geändert werden (erweitern statt extend, ..)

**Comment by PaulFrost** [comment]
Danke für das Review ;-)
